all: dimaos.bin

# Build the kernel binary
./out/kernel.bin: ./out/kernel_entry.o ./out/kernel.o ./out/lib/video/vga.o
	/usr/local/i386elfgcc/bin/i386-elf-ld -Ttext 0x1000 $^ -o $@ --oformat binary 

# Build the kernel itself
./out/kernel.o : ./src/kernel/kernel.c
	/usr/local/i386elfgcc/bin/i386-elf-gcc -ffreestanding -c $< -o $@ -I./src/kernel/

# Build the kernel entry
./out/kernel_entry.o : ./src/boot/kernel_entry.asm
	nasm -i./src $< -f elf -o $@

# Build all the kernel modules
./out/lib/video/vga.o : ./src/kernel/video/vga.c
	mkdir -p ./out/lib/video 2>/dev/null
	/usr/local/i386elfgcc/bin/i386-elf-gcc -ffreestanding -c $< -o $@

# Build the bootloader
./out/boot.o : ./src/boot/boot.asm
	nasm -i./src $< -f bin -o $@

dimaos.bin: ./out/boot.o ./out/kernel.bin
	cat $^ > dimaos.bin

kernel.dis : kernel.bin
	ndisasm -b 32 $< > $@

run: all
	bochs.exe -q

clean:
	rm -rf *.bin *.dis *.o dimaos.bin *.map
	rm -rf ./out/*
